Update django.yml

diff --git a/.github/workflows/django.yml b/.github/workflows/django.yml
--- a/.github/workflows/django.yml
+++ b/.github/workflows/django.yml
@@ -50,14 +50,13 @@ jobs:
           docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:latest
 
       - name: Run Trivy Security Scan
-  uses: aquasecurity/trivy-action@master
-  with:
-    image-ref: ${{ env.IMAGE_NAME }}:${{ env.TAG }}
-    format: table
-    exit-code: "1" # Fail pipeline on critical/high vulnerabilities
-    vuln-type: os,library
-    severity: CRITICAL,HIGH
-
+        uses: aquasecurity/trivy-action@master
+        with:
+          image-ref: ${{ env.IMAGE_NAME }}:${{ env.TAG }}
+          format: table
+          exit-code: "1"  # Fail pipeline on critical/high vulnerabilities
+          vuln-type: os,library
+          severity: CRITICAL,HIGH
 
       - name: Push Docker Image
         run: |
@@ -92,7 +91,7 @@ jobs:
             docker compose -f /home/${{ secrets.REMOTE_USER }}/horilla/docker-compose.yml up -d --build
 
             echo "Running Django Migrations (optional)..."
-            docker exec web python manage.py migrate
+            docker exec web python manage.py migrate || true
 
             echo "Cleaning up old images..."
             docker image prune -f
